version: '2'

vars:
  EXE: buildkite-stats{{exeExt}}

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - ./{{.EXE}} --buildkite-token "$BUILDKITE_API_TOKEN" --branch "$BRANCH" --buildkite-org "$BUILDKITE_ORGANIZATION"

  build:
    sources:
      - "*.go"
    cmds:
      - go build -v -o {{.EXE}}

  clean:
    cmds:
      - rm -vf {{.EXE}}
