version: '2'

vars:
  EXE: tink-buildkite-stats{{exeExt}}

tasks:
  default:
    cmds:
      - task: run-serve

  run-serve:
    deps:
      - build
    cmds:
      - |
        ./{{.EXE}} --buildkite-token "$BUILDKITE_API_TOKEN" --buildkite-org "$BUILDKITE_ORGANIZATION" --memcache 127.0.0.1:11211 serve --report='{"name": "Slow staging builds", "from": "started", "to": "finished", "pipelines": ".*", "branches": "^staging$", "group": "{{"{{"}}.Pipeline.Name{{"}}"}}"}'

  build:
    sources:
      - "*.go"
    cmds:
      - go build -v -o {{.EXE}}

  clean:
    cmds:
      - rm -vf {{.EXE}}
